!include <C4/C4_Component>

LAYOUT_WITH_LEGEND()
    ContainerQueue(kafka, "Message Broker", "Apache Kafka", "Xử lý các sự kiện bất đồng bộ giữa các dịch vụ")
    Container(action, "Action Service", "Node.js, Weaviate, Express", "Chịu trách nhiệm thực thi các hành động nghiệp vụ như truy vấn RAG và quản lý đơn hàng")
    System_Ext(LLM,"LLM Provider", "Nền tảng cung cấp mô hình ngôn ngữ lớn (LLM) để sinh phản hồi")
    ContainerDb(db, "Cơ sở dữ liệu", "MongoDB", "Lưu trữ thông tin người dùng, tin nhắn, cấu hình hệ thống")

Container_Boundary(server, "Answer Generation Service"){
    Component(kafkacli, "Kafka Client", "Kafka producer/consumer", "Xử lý sự kiện bất đồng bộ")
    Component(graph, "Graph", "LangGraph graph", "Xử lý các tác vụ sinh phản hồi và gọi hành động")
    Component(decompose, "Decompose node", "LangGraph node", "Phân tích tin nhắn khách hàng")
    Component(agent, "reAct Agent node", "LangGraph node", "Sinh phản hồi và gọi hành động tương ứng")
    Component(tool, "Tool Store", "LangChain tool", "Các công cụ để agent gọi")
    Component(rag, "Tool for Rag", "LangChain tool", "Công cụ để agent truy vấn dữ liệu RAG")
    Component(reservation, "Tool for Reservation", "LangChain tool", "Công cụ để agent quản lý đặt chỗ")
    Component(imagesearch, "Tool for Image Search", "LangChain tool", "Công cụ để agent tìm kiếm hình ảnh")
    Component(context,"Prompt builder", "helper function", "Xây dựng ngữ cảnh cho agent")
    Component(cust, "Cusstomer info", "LangGraph node", "Trích xuất thông tin khách hàng để lưu lại")
    Rel_R(kafkacli, graph, "Consume LLM_Mes", "Kafka consumer")
    Rel_L(graph, kafkacli, "Produce Rec_Ans", "Kafka producer")
    Rel_D(graph, decompose, "Contains")
    Rel_D(graph, agent, "Contains")
    Rel_D(graph, cust, "Contains")
    Rel_Neighbor(agent,decompose , "Uses")
    Rel_D(agent, tool, "Uses")
    Rel_D(tool, rag, "Contains")
    Rel_D(tool, reservation, "Contains")
    Rel_D(tool, imagesearch, "Contains")
    Rel_D(agent, context, "Uses")
}
BiRel_L(kafkacli,kafka, "Connect")
Rel_L(agent, LLM, "Gọi mô hình sinh phản hồi", "HTTP REST")
Rel_L(tool, action, "Gọi các công cụ", "HTTP REST")
Rel_Neighbor(context, db, "Truy xuất dữ liệu doanh nghiệp", "Mongo client")
Rel(graph, db, "Truy xuất thông tin khách hàng", "Mongo client")
Rel_D(cust, db, "Lưu thông tin khách hàng", "Mongo client")